/**
 * AntD Token Mapping — Shared Default Values & Seed→Component Mapping Tables
 *
 * Central dictionary for AntD v5 token hierarchy:
 *   Seed → Map → Alias → Component
 *
 * All token values are CSS strings.
 */

'use strict';

// ── Seed Tokens ────────────────────────────────────────────────────────────
// Brand-defining inputs. AntD v5 uses these to derive map & alias tokens.
const SEED_TOKENS = {
  // Brand colors
  colorPrimary:   '#1677ff',
  colorSuccess:   '#52c41a',
  colorWarning:   '#faad14',
  colorError:     '#ff4d4f',
  colorInfo:      '#1677ff',

  // Neutral
  colorBgBase:    '#ffffff',
  colorTextBase:  '#000000',

  // Geometry
  borderRadius:    '6px',
  wireframe:       'false',

  // Motion
  motionUnit:      '0.1',
  motionBase:      '0',
};

// ── Map Tokens ─────────────────────────────────────────────────────────────
// Derived from seed tokens via AntD's built-in color algorithms.
// These represent the actual palette used by components.
const MAP_TOKENS = {
  // Primary color map
  colorPrimaryBg:         '#e6f4ff',
  colorPrimaryBgHover:    '#bae0ff',
  colorPrimaryBorder:     '#91caff',
  colorPrimaryBorderHover:'#69b1ff',
  colorPrimaryHover:      '#4096ff',
  colorPrimaryActive:     '#0958d9',
  colorPrimaryText:       '#1677ff',
  colorPrimaryTextHover:  '#4096ff',
  colorPrimaryTextActive: '#0958d9',

  // Success color map
  colorSuccessBg:         '#f6ffed',
  colorSuccessBorder:     '#b7eb8f',
  colorSuccessHover:      '#73d13d',
  colorSuccessActive:     '#389e0d',
  colorSuccessText:       '#52c41a',
  colorSuccessTextHover:  '#73d13d',
  colorSuccessTextActive: '#389e0d',

  // Warning color map
  colorWarningBg:         '#fffbe6',
  colorWarningBorder:     '#ffe58f',
  colorWarningHover:      '#ffc53d',
  colorWarningActive:     '#d48806',
  colorWarningText:       '#faad14',
  colorWarningTextHover:  '#ffc53d',
  colorWarningTextActive: '#d48806',

  // Error color map
  colorErrorBg:           '#fff2f0',
  colorErrorBorder:       '#ffccc7',
  colorErrorHover:        '#ff7875',
  colorErrorActive:       '#d9363e',
  colorErrorText:         '#ff4d4f',
  colorErrorTextHover:    '#ff7875',
  colorErrorTextActive:   '#d9363e',

  // Info color map
  colorInfoBg:            '#e6f4ff',
  colorInfoBorder:        '#91caff',
  colorInfoHover:         '#4096ff',
  colorInfoActive:        '#0958d9',
  colorInfoText:          '#1677ff',
  colorInfoTextHover:     '#4096ff',
  colorInfoTextActive:    '#0958d9',

  // Neutral / container
  colorBgContainer:        '#ffffff',
  colorBgElevated:         '#ffffff',
  colorBgLayout:           '#f5f5f5',
  colorBgSpotlight:        '#000000',
  colorBgMask:             'rgba(0, 0, 0, 0.45)',
  colorBorder:             '#d9d9d9',
  colorBorderSecondary:    '#f0f0f0',

  // Text
  colorText:               'rgba(0, 0, 0, 0.88)',
  colorTextSecondary:      'rgba(0, 0, 0, 0.65)',
  colorTextTertiary:       'rgba(0, 0, 0, 0.45)',
  colorTextQuaternary:     'rgba(0, 0, 0, 0.25)',

  // Fill
  colorFill:               'rgba(0, 0, 0, 0.15)',
  colorFillSecondary:      'rgba(0, 0, 0, 0.06)',
  colorFillTertiary:       'rgba(0, 0, 0, 0.04)',
  colorFillQuaternary:     'rgba(0, 0, 0, 0.02)',

  // Typography
  fontFamily:              "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  fontFamilyCode:          "'SF Mono', Monaco, Inconsolata, 'Fira Mono', 'Droid Sans Mono', 'Courier New', monospace",
  fontSize:                '14px',
  fontSizeSM:              '12px',
  fontSizeLG:              '16px',
  fontSizeXL:              '20px',
  fontWeightStrong:        '600',

  // Line height
  lineHeight:              '1.5715',
  lineHeightSM:            '1.5',
  lineHeightLG:            '1.5',
  lineHeightHeading1:      '1.21',
  lineHeightHeading2:      '1.27',
  lineHeightHeading3:      '1.33',
  lineHeightHeading4:      '1.4',
  lineHeightHeading5:      '1.5',

  // Spacing (margin/padding scale)
  marginXXS:               '4px',
  marginXS:                '8px',
  marginSM:                '12px',
  margin:                  '16px',
  marginMD:                '20px',
  marginLG:                '24px',
  marginXL:                '32px',
  marginXXL:               '48px',
  paddingXXS:              '4px',
  paddingXS:               '8px',
  paddingSM:               '12px',
  padding:                 '16px',
  paddingMD:               '20px',
  paddingLG:               '24px',
  paddingXL:               '32px',
  paddingXXL:              '48px',

  // Box shadow
  boxShadow:               '0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)',
  boxShadowSecondary:      '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
  boxShadowTertiary:       '0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)',
  boxShadowPopoverArrow:   '2px 2px 5px rgba(0, 0, 0, 0.05)',
};

// ── Alias Tokens ───────────────────────────────────────────────────────────
// Higher-level semantic tokens derived from map tokens.
const ALIAS_TOKENS = {
  // Color aliases
  colorFill:              'rgba(0, 0, 0, 0.15)',
  colorFillSecondary:     'rgba(0, 0, 0, 0.06)',
  colorFillTertiary:      'rgba(0, 0, 0, 0.04)',
  colorFillQuaternary:    'rgba(0, 0, 0, 0.02)',
  colorBorder:            '#d9d9d9',
  colorBorderSecondary:   '#f0f0f0',
  colorTextSecondary:     'rgba(0, 0, 0, 0.65)',
  colorTextTertiary:      'rgba(0, 0, 0, 0.45)',
  colorTextQuaternary:    'rgba(0, 0, 0, 0.25)',
  colorBgElevated:        '#ffffff',
  colorBgContainer:       '#ffffff',
  colorBgLayout:          '#f5f5f5',
  colorBgSpotlight:       '#000000',
  colorBgMask:            'rgba(0, 0, 0, 0.45)',

  // Control
  controlHeight:           '32px',
  controlHeightSM:         '24px',
  controlHeightLG:         '40px',
  controlOutline:          'rgba(22, 119, 255, 0.1)',
  controlOutlineWidth:     '2px',
  controlTmpOutline:       'rgba(0, 0, 0, 0.02)',
  controlPaddingHorizontal: '12px',
  controlPaddingHorizontalSM: '8px',

  // Font
  fontSize:                '14px',
  fontSizeSM:              '12px',
  fontSizeLG:              '16px',
  fontSizeXL:              '20px',
  fontSizeHeading1:        '38px',
  fontSizeHeading2:        '30px',
  fontSizeHeading3:        '24px',
  fontSizeHeading4:        '20px',
  fontSizeHeading5:        '16px',
  fontFamily:              "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  fontWeightStrong:        '600',

  // Line height
  lineHeight:              '1.5715',
  lineHeightSM:            '1.5',
  lineHeightLG:            '1.5',
  lineHeightHeading1:      '1.21',
  lineHeightHeading2:      '1.27',
  lineHeightHeading3:      '1.33',
  lineHeightHeading4:      '1.4',
  lineHeightHeading5:      '1.5',

  // Motion
  motionDurationFast:     '0.1s',
  motionDurationMid:      '0.2s',
  motionDurationSlow:     '0.3s',
  motionEaseOutBack:      'cubic-bezier(0.34, 1.56, 0.64, 1)',
  motionEaseInBack:       'cubic-bezier(0.36, 0, 0.66, -0.56)',
  motionEaseInOut:        'cubic-bezier(0.65, 0, 0.35, 1)',
  motionEaseOut:          'cubic-bezier(0.15, 0.6, 0.35, 1)',
  motionEaseIn:           'cubic-bezier(0.55, 0.08, 0.68, 0.53)',
};

// ── Component Tokens ───────────────────────────────────────────────────────
// Per-component tokens that map seed/map values to component-specific CSS vars.
const COMPONENT_TOKENS = {
  Button: {
    colorPrimary:           '#1677ff',
    colorPrimaryHover:      '#4096ff',
    colorPrimaryActive:     '#0958d9',
    colorBgContainer:       '#ffffff',
    colorBgTextHover:       'rgba(0, 0, 0, 0.04)',
    colorBgTextActive:      'rgba(0, 0, 0, 0.08)',
    colorBorder:            '#d9d9d9',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextDisabled:      'rgba(0, 0, 0, 0.25)',
    colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
    borderColorDisabled:    '#d9d9d9',
    defaultShadow:          '0 2px 0 rgba(0, 0, 0, 0.02)',
    primaryShadow:          '0 2px 0 rgba(5, 145, 255, 0.1)',
    dangerShadow:           '0 2px 0 rgba(255, 77, 79, 0.1)',
    dangerColor:            '#ff4d4f',
    dangerColorHover:       '#ff7875',
    dangerColorActive:      '#d9363e',
    dangerBorderColor:      '#ff4d4f',
    onlyIconSize:           '16px',
    paddingBlock:           '4px',
    paddingInline:          '15px',
    paddingBlockSM:         '0px',
    paddingInlineSM:        '7px',
    paddingBlockLG:         '7px',
    paddingInlineLG:        '15px',
    fontSize:               '14px',
    fontSizeLG:             '16px',
    fontWeight:             '400',
    lineHeight:             '1.5715',
    borderRadius:           '6px',
    controlHeight:          '32px',
    controlHeightSM:        '24px',
    controlHeightLG:        '40px',
    contentFontSize:        '14px',
    contentFontSizeSM:      '14px',
    contentFontSizeLG:      '16px',
    groupBorderColor:       '#4096ff',
    linkHoverBg:            'transparent',
    onlyIconSizeSM:         '14px',
    onlyIconSizeLG:         '18px',
  },

  Input: {
    colorBgContainer:       '#ffffff',
    colorBorder:            '#d9d9d9',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextPlaceholder:   'rgba(0, 0, 0, 0.25)',
    colorIcon:              'rgba(0, 0, 0, 0.45)',
    colorPrimary:           '#1677ff',
    colorPrimaryHover:      '#4096ff',
    colorError:             '#ff4d4f',
    colorErrorOutline:      'rgba(255, 77, 79, 0.1)',
    colorWarning:           '#faad14',
    colorWarningOutline:    'rgba(250, 173, 20, 0.1)',
    colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
    colorTextDisabled:      'rgba(0, 0, 0, 0.25)',
    addonBg:                'rgba(0, 0, 0, 0.02)',
    hoverBg:                '#ffffff',
    activeBg:               '#ffffff',
    activeBorderColor:      '#4096ff',
    hoverBorderColor:       '#4096ff',
    activeShadow:           '0 0 0 2px rgba(22, 119, 255, 0.1)',
    errorActiveShadow:      '0 0 0 2px rgba(255, 77, 79, 0.1)',
    warningActiveShadow:    '0 0 0 2px rgba(250, 173, 20, 0.1)',
    paddingBlock:           '4px',
    paddingInline:          '11px',
    paddingBlockSM:         '0px',
    paddingInlineSM:        '7px',
    paddingBlockLG:         '6px',
    paddingInlineLG:        '11px',
    fontSize:               '14px',
    fontSizeLG:             '16px',
    lineHeight:             '1.5715',
    borderRadius:           '6px',
    controlHeight:          '32px',
    controlHeightSM:        '24px',
    controlHeightLG:        '40px',
    inputFontSize:          '14px',
    inputFontSizeSM:        '14px',
    inputFontSizeLG:        '16px',
  },

  Select: {
    colorBgContainer:       '#ffffff',
    colorBorder:            '#d9d9d9',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextPlaceholder:   'rgba(0, 0, 0, 0.25)',
    colorPrimary:           '#1677ff',
    colorPrimaryHover:      '#4096ff',
    colorBgElevated:        '#ffffff',
    colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
    colorTextDisabled:      'rgba(0, 0, 0, 0.25)',
    colorIcon:              'rgba(0, 0, 0, 0.45)',
    colorIconHover:         'rgba(0, 0, 0, 0.88)',
    optionSelectedBg:       '#e6f4ff',
    optionSelectedColor:    'rgba(0, 0, 0, 0.88)',
    optionActiveBg:         'rgba(0, 0, 0, 0.04)',
    optionPadding:          '5px 12px',
    optionFontSize:         '14px',
    optionLineHeight:       '1.5715',
    multipleItemBg:         'rgba(0, 0, 0, 0.06)',
    multipleItemBorderColor:'transparent',
    multipleItemHeight:     '24px',
    selectorBg:             '#ffffff',
    clearBg:                '#ffffff',
    singleItemHeight:       '32px',
    activeBorderColor:      '#4096ff',
    hoverBorderColor:       '#4096ff',
    activeShadow:           '0 0 0 2px rgba(22, 119, 255, 0.1)',
    paddingBlock:           '4px',
    paddingInline:          '11px',
    paddingBlockSM:         '0px',
    paddingInlineSM:        '7px',
    paddingBlockLG:         '6px',
    paddingInlineLG:        '11px',
    fontSize:               '14px',
    fontSizeLG:             '16px',
    lineHeight:             '1.5715',
    borderRadius:           '6px',
    controlHeight:          '32px',
    controlHeightSM:        '24px',
    controlHeightLG:        '40px',
  },

  Table: {
    colorBgContainer:       '#ffffff',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextHeading:       'rgba(0, 0, 0, 0.88)',
    colorBorder:            '#f0f0f0',
    colorBorderSecondary:   '#f0f0f0',
    headerBg:               '#fafafa',
    headerColor:            'rgba(0, 0, 0, 0.88)',
    headerSortActiveBg:     '#f0f0f0',
    headerSortHoverBg:      '#f5f5f5',
    headerFilterHoverBg:    '#f0f0f0',
    bodySortHoverBg:        '#fafafa',
    rowHoverBg:             '#fafafa',
    rowSelectedBg:          '#e6f4ff',
    rowSelectedHoverBg:     '#bae0ff',
    rowExpandedBg:          '#fafafa',
    cellPaddingBlock:       '16px',
    cellPaddingInline:      '16px',
    cellPaddingBlockMD:     '12px',
    cellPaddingInlineMD:    '12px',
    cellPaddingBlockSM:     '8px',
    cellPaddingInlineSM:    '8px',
    borderColor:            '#f0f0f0',
    headerBorderRadius:     '6px',
    footerBg:               '#fafafa',
    footerColor:            'rgba(0, 0, 0, 0.88)',
    cellFontSize:           '14px',
    cellFontSizeMD:         '14px',
    cellFontSizeSM:         '14px',
    headerSplitColor:       '#f0f0f0',
    fixedHeaderSortActiveBg:'#f0f0f0',
    headerFilterHoverColor: 'rgba(0, 0, 0, 0.88)',
    filterDropdownBg:       '#ffffff',
    filterDropdownMenuBg:   '#ffffff',
    expandIconBg:           '#ffffff',
    selectionColumnWidth:   '48px',
    stickyScrollBarBg:      'rgba(0, 0, 0, 0.25)',
    stickyScrollBarBorderRadius: '100px',
  },

  Card: {
    colorBgContainer:       '#ffffff',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextHeading:       'rgba(0, 0, 0, 0.88)',
    colorBorder:            '#f0f0f0',
    colorBorderSecondary:   '#f0f0f0',
    headerBg:               'transparent',
    headerFontSize:         '16px',
    headerFontSizeSM:       '14px',
    headerHeight:           '56px',
    headerHeightSM:         '38px',
    actionsBg:              '#ffffff',
    actionsLiMargin:        '12px 0',
    tabsMargin:             '-12px -16px',
    extraFontSize:          '14px',
    bodyPadding:            '24px',
    bodyPaddingSM:           '12px',
    borderRadius:           '6px',
    paddingBase:            '24px',
    paddingSM:              '12px',
  },

  Modal: {
    colorBgContainer:       '#ffffff',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextHeading:       'rgba(0, 0, 0, 0.88)',
    colorBorder:            '#f0f0f0',
    colorPrimary:           '#1677ff',
    colorPrimaryHover:      '#4096ff',
    headerBg:               'transparent',
    headerFontSize:         '16px',
    headerLineHeight:       '1.5',
    headerPaddingVertical:  '16px',
    headerPaddingHorizontal:'24px',
    contentBg:              '#ffffff',
    footerBg:               'transparent',
    footerPaddingVertical:  '16px',
    footerPaddingHorizontal:'24px',
    bodyPadding:            '24px',
    bodyPaddingVertical:    '12px',
    titleColor:             'rgba(0, 0, 0, 0.88)',
    titleFontSize:          '16px',
    borderRadius:           '6px',
    borderRadiusLG:         '8px',
    boxShadow:              '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
    motionDurationMid:      '0.2s',
    motionDurationSlow:     '0.3s',
    marginXS:               '8px',
    paddingContentHorizontal: '16px',
    paddingMD:              '20px',
    paddingContentVertical: '12px',
    padding:                '16px',
    gap:                    '8px',
  },

  Tag: {
    colorPrimary:           '#1677ff',
    colorPrimaryBg:         '#e6f4ff',
    colorPrimaryBorder:     '#91caff',
    colorSuccess:           '#52c41a',
    colorSuccessBg:         '#f6ffed',
    colorSuccessBorder:     '#b7eb8f',
    colorWarning:           '#faad14',
    colorWarningBg:         '#fffbe6',
    colorWarningBorder:     '#ffe58f',
    colorError:             '#ff4d4f',
    colorErrorBg:           '#fff2f0',
    colorErrorBorder:       '#ffccc7',
    colorInfo:              '#1677ff',
    colorInfoBg:            '#e6f4ff',
    colorInfoBorder:        '#91caff',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextSecondary:     'rgba(0, 0, 0, 0.65)',
    colorBorder:            '#d9d9d9',
    colorBgContainer:       '#ffffff',
    borderRadius:           '4px',
    fontSize:               '12px',
    lineHeight:             '1.5',
    paddingInline:          '7px',
    paddingBlock:           '0px',
    marginXS:               '4px',
    defaultBg:              '#fafafa',
    defaultColor:           'rgba(0, 0, 0, 0.88)',
  },

  Badge: {
    colorPrimary:           '#1677ff',
    colorError:             '#ff4d4f',
    colorSuccess:           '#52c41a',
    colorWarning:           '#faad14',
    colorInfo:              '#1677ff',
    colorText:              '#ffffff',
    colorBorder:            '#ffffff',
    fontSize:               '12px',
    fontSizeSM:             '12px',
    lineHeight:             '1.5',
    lineHeightSM:           '1.5',
    height:                 '20px',
    heightSM:               '14px',
    paddingInline:          '6px',
    paddingInlineSM:        '4px',
    dotSize:                '6px',
    dotSizeSM:              '6px',
    textFontSize:           '12px',
    textFontSizeSM:         '12px',
    textFontWeight:         '400',
    statusSize:             '6px',
    borderRadius:           '10px',
    borderRadiusSM:         '7px',
    indicatorBg:            '#ff4d4f',
    indicatorShadow:        '0 0 0 1px #ffffff',
  },

  Tabs: {
    colorPrimary:           '#1677ff',
    colorPrimaryHover:      '#4096ff',
    colorPrimaryActive:     '#0958d9',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextSecondary:     'rgba(0, 0, 0, 0.65)',
    colorTextDisabled:      'rgba(0, 0, 0, 0.25)',
    colorBgContainer:       '#ffffff',
    colorBorder:            '#f0f0f0',
    colorBorderSecondary:   '#f0f0f0',
    inkBarColor:            '#1677ff',
    itemColor:              'rgba(0, 0, 0, 0.88)',
    itemHoverColor:         '#4096ff',
    itemSelectedColor:      '#1677ff',
    itemActiveColor:        '#0958d9',
    fontWeight:             '400',
    fontSize:               '14px',
    fontSizeLG:             '16px',
    lineHeight:             '1.5715',
    horizontalMargin:       '0 0 0 32px',
    horizontalGutter:       '32px',
    cardBg:                 '#fafafa',
    cardHeight:             '40px',
    cardPadding:            '8px 16px',
    cardPaddingSM:          '4px 12px',
    cardGutter:             '2px',
    horizontalItemPadding:  '12px 0',
    verticalItemPadding:    '8px 24px',
    inkBarHeight:           '2px',
    horizontalItemMargin:   '0 32px 0 0',
    borderRadius:           '6px',
    motionDurationSlow:     '0.3s',
  },

  Menu: {
    colorPrimary:           '#1677ff',
    colorPrimaryHover:      '#4096ff',
    colorPrimaryActive:     '#0958d9',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextSecondary:     'rgba(0, 0, 0, 0.65)',
    colorTextDisabled:      'rgba(0, 0, 0, 0.25)',
    colorBgContainer:       '#ffffff',
    colorBgElevated:        '#ffffff',
    colorBgSubMenu:         '#ffffff',
    colorBorder:            '#f0f0f0',
    colorBorderSecondary:   '#f0f0f0',
    itemBg:                 'transparent',
    itemColor:              'rgba(0, 0, 0, 0.88)',
    itemHoverBg:            'rgba(0, 0, 0, 0.04)',
    itemHoverColor:         '#4096ff',
    itemSelectedBg:         '#e6f4ff',
    itemSelectedColor:      '#1677ff',
    itemActiveBg:           'rgba(0, 0, 0, 0.06)',
    popupBg:                '#ffffff',
    groupTitleColor:        'rgba(0, 0, 0, 0.45)',
    groupTitleFontSize:     '14px',
    groupTitleLineHeight:   '1.5715',
    horizontalItemBorderRadius: '6px',
    verticalItemBorderRadius:     '6px',
    itemMarginBlock:        '4px',
    itemMarginInline:        '4px',
    itemHeight:             '40px',
    itemPaddingInline:       '16px',
    iconSize:               '16px',
    iconMarginInlineEnd:     '10px',
    collapsedWidth:         '48px',
    collapsedIconSize:      '16px',
    subMenuItemBg:          'transparent',
    subMenuItemHeight:      '40px',
    subMenuItemPaddingInline: '16px',
    inlineIndent:           '24px',
    dropdownWidth:          '160px',
    borderRadius:           '6px',
    motionDurationMid:      '0.2s',
    motionDurationSlow:     '0.3s',
    fontSize:               '14px',
    fontSizeLG:             '14px',
    fontWeight:             '400',
    lineHeight:             '1.5715',
    padding:                '4px',
    paddingXS:              '8px',
    marginXS:               '4px',
  },

  Form: {
    colorBgContainer:       '#ffffff',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextSecondary:     'rgba(0, 0, 0, 0.65)',
    colorError:             '#ff4d4f',
    colorWarning:           '#faad14',
    colorSuccess:           '#52c41a',
    colorPrimary:           '#1677ff',
    colorBorder:            '#d9d9d9',
    colorBorderSecondary:   '#f0f0f0',
    labelColor:             'rgba(0, 0, 0, 0.88)',
    labelFontSize:          '14px',
    labelLineHeight:        '1.5715',
    labelRequiredMarkColor: '#ff4d4f',
    labelColonMarginInline: '4px',
    itemMarginBottom:       '24px',
    itemMarginBottomSM:     '16px',
    verticalLabelPadding:   '0 0 4px',
    verticalLabelMargin:    '0',
    controlHeight:          '32px',
    controlHeightSM:        '24px',
    controlHeightLG:        '40px',
    fontSize:               '14px',
    fontSizeLG:             '16px',
    lineHeight:             '1.5715',
    borderRadius:           '6px',
    paddingXS:              '8px',
    marginXS:               '8px',
    helpFontSize:           '14px',
    extraFontSize:          '14px',
    extraColor:             'rgba(0, 0, 0, 0.45)',
  },

  DatePicker: {
    colorBgContainer:       '#ffffff',
    colorBorder:            '#d9d9d9',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextPlaceholder:   'rgba(0, 0, 0, 0.25)',
    colorPrimary:           '#1677ff',
    colorPrimaryHover:      '#4096ff',
    colorPrimaryActive:     '#0958d9',
    colorBgElevated:        '#ffffff',
    colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
    colorTextDisabled:      'rgba(0, 0, 0, 0.25)',
    colorIcon:              'rgba(0, 0, 0, 0.45)',
    colorIconHover:         'rgba(0, 0, 0, 0.88)',
    colorLink:              '#1677ff',
    colorLinkHover:         '#4096ff',
    colorLinkActive:        '#0958d9',
    cellHoverBg:            'rgba(0, 0, 0, 0.04)',
    cellActiveBg:           '#e6f4ff',
    cellRangeBorderColor:   'transparent',
    cellHoverBorderRadius:  '6px',
    cellWidth:              '36px',
    cellHeight:             '36px',
    textCellHeight:         '28px',
    withoutTimeCellHeight:  '52px',
    multipleItemBg:         'rgba(0, 0, 0, 0.06)',
    multipleItemBorderColor:'transparent',
    activeBorderColor:      '#4096ff',
    hoverBorderColor:       '#4096ff',
    activeShadow:           '0 0 0 2px rgba(22, 119, 255, 0.1)',
    paddingBlock:           '4px',
    paddingInline:          '11px',
    paddingBlockSM:         '0px',
    paddingInlineSM:        '7px',
    paddingBlockLG:         '6px',
    paddingInlineLG:        '11px',
    fontSize:               '14px',
    fontSizeLG:             '16px',
    lineHeight:             '1.5715',
    borderRadius:           '6px',
    controlHeight:          '32px',
    controlHeightSM:        '24px',
    controlHeightLG:        '40px',
  },

  Checkbox: {
    colorPrimary:           '#1677ff',
    colorPrimaryHover:      '#4096ff',
    colorPrimaryActive:     '#0958d9',
    colorBgContainer:       '#ffffff',
    colorBorder:            '#d9d9d9',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextDisabled:      'rgba(0, 0, 0, 0.25)',
    colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
    colorCheck:             '#ffffff',
    colorCheckDisabled:     'rgba(0, 0, 0, 0.25)',
    borderRadius:           '4px',
    lineHeight:             '1.5',
    fontSize:               '14px',
    lineWidth:              '1px',
    marginXS:               '8px',
    controlInteractiveSize: '16px',
    checkboxSize:           '16px',
    checkboxSizeSM:         '14px',
    checkboxBg:             '#ffffff',
    checkboxCheckColor:     '#1677ff',
    checkboxBorderColor:    '#d9d9d9',
  },

  Radio: {
    colorPrimary:           '#1677ff',
    colorPrimaryHover:      '#4096ff',
    colorPrimaryActive:     '#0958d9',
    colorBgContainer:       '#ffffff',
    colorBorder:            '#d9d9d9',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextDisabled:      'rgba(0, 0, 0, 0.25)',
    colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
    colorCheck:             '#1677ff',
    colorCheckDisabled:     'rgba(0, 0, 0, 0.25)',
    borderRadius:           '100px',
    lineHeight:             '1.5',
    fontSize:               '14px',
    lineWidth:              '1px',
    marginXS:               '8px',
    radioSize:              '16px',
    radioSizeSM:            '14px',
    dotSize:                '8px',
    dotSizeDisabled:        '8px',
    radioBg:                '#ffffff',
    radioCheckColor:        '#1677ff',
    radioBorderColor:       '#d9d9d9',
    buttonBg:               '#ffffff',
    buttonColor:            'rgba(0, 0, 0, 0.88)',
    buttonCheckedBg:        '#ffffff',
    buttonCheckedColor:     '#1677ff',
    buttonSolidCheckedBg:   '#1677ff',
    buttonSolidCheckedColor:'#ffffff',
    buttonSolidCheckedHoverBg: '#4096ff',
    buttonSolidCheckedActiveBg: '#0958d9',
  },

  Switch: {
    colorPrimary:           '#1677ff',
    colorPrimaryHover:      '#4096ff',
    colorPrimaryActive:     '#0958d9',
    colorBgContainer:       'rgba(0, 0, 0, 0.25)',
    colorText:              '#ffffff',
    colorTextDisabled:      'rgba(0, 0, 0, 0.25)',
    colorBgContainerDisabled: 'rgba(0, 0, 0, 0.06)',
    trackPadding:           '0px',
    trackMinWidth:          '44px',
    trackMinWidthSM:        '28px',
    trackHeight:            '22px',
    trackHeightSM:          '16px',
    handleSize:             '18px',
    handleSizeSM:           '12px',
    handleShadow:           '0 2px 4px 0 rgba(0, 35, 11, 0.2)',
    innerMaxMargin:         '24px',
    innerMaxMarginSM:       '14px',
    innerMinMargin:         '6px',
    innerMinMarginSM:       '4px',
    borderRadius:           '100px',
    borderRadiusSM:         '100px',
    fontSize:               '14px',
    fontSizeSM:             '12px',
    loadingIconSize:        '12px',
    loadingIconSizeSM:      '8px',
  },

  Slider: {
    colorPrimary:           '#1677ff',
    colorPrimaryHover:      '#4096ff',
    colorPrimaryActive:     '#0958d9',
    colorBgContainer:       '#ffffff',
    colorFill:              'rgba(0, 0, 0, 0.06)',
    colorFillSecondary:     'rgba(0, 0, 0, 0.15)',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextDisabled:      'rgba(0, 0, 0, 0.25)',
    colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
    railBg:                 'rgba(0, 0, 0, 0.06)',
    railHoverBg:            'rgba(0, 0, 0, 0.06)',
    trackBg:                '#1677ff',
    trackHoverBg:           '#4096ff',
    handleColor:            '#1677ff',
    handleHoverColor:       '#4096ff',
    handleActiveColor:      '#0958d9',
    handleSize:             '14px',
    handleSizeHover:        '16px',
    handleLineWidth:        '2px',
    handleLineWidthHover:   '2px',
    dotSize:                '8px',
    dotBorderColor:         '#d9d9d9',
    dotActiveBorderColor:   '#1677ff',
    railSize:               '4px',
    borderRadius:           '2px',
    fontSize:               '14px',
    lineHeight:             '1.5715',
    margin:                 '16px',
    marginXS:               '8px',
  },

  Progress: {
    colorPrimary:           '#1677ff',
    colorSuccess:           '#52c41a',
    colorWarning:           '#faad14',
    colorError:             '#ff4d4f',
    colorInfo:              '#1677ff',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextSecondary:     'rgba(0, 0, 0, 0.65)',
    colorBgContainer:       'rgba(0, 0, 0, 0.06)',
    colorFill:              'rgba(0, 0, 0, 0.06)',
    borderRadius:           '100px',
    lineHeight:             '1.5',
    fontSize:               '14px',
    marginXS:               '8px',
    defaultStrokeColor:     '#1677ff',
    remainingColor:         'rgba(0, 0, 0, 0.06)',
    trailColor:             'rgba(0, 0, 0, 0.06)',
    textColor:              'rgba(0, 0, 0, 0.88)',
    circleTextColor:        'rgba(0, 0, 0, 0.88)',
    circleTextFontSize:     '24px',
    stepColor:              '#1677ff',
    stepMargin:             '2px',
    strokeLinecap:          'round',
    formatFontSize:         '14px',
    gapDegree:              '0',
    gapPosition:            'bottom',
  },

  Tooltip: {
    colorBgSpotlight:       '#000000',
    colorText:              '#ffffff',
    borderRadius:           '4px',
    fontSize:               '12px',
    lineHeight:             '1.5',
    padding:                '6px 8px',
    paddingSM:              '4px 6px',
    arrowOffset:            '16px',
    arrowSize:              '8px',
    arrowTailSize:          '4px',
    boxShadow:              '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
    motionDurationMid:      '0.2s',
    motionDurationSlow:     '0.3s',
  },

  Popover: {
    colorBgElevated:        '#ffffff',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextHeading:       'rgba(0, 0, 0, 0.88)',
    colorBorder:            '#f0f0f0',
    borderRadius:           '6px',
    fontSize:               '14px',
    fontSizeHeading:        '14px',
    lineHeight:             '1.5715',
    padding:                '12px',
    paddingSM:              '8px',
    titleMinWidth:          '177px',
    titlePadding:           '12px 16px',
    innerPadding:           '8px 12px',
    arrowOffset:            '16px',
    arrowSize:              '12px',
    arrowTailSize:          '6px',
    boxShadow:              '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
    motionDurationMid:      '0.2s',
    motionDurationSlow:     '0.3s',
  },

  Drawer: {
    colorBgContainer:       '#ffffff',
    colorText:              'rgba(0, 0, 0, 0.88)',
    colorTextHeading:       'rgba(0, 0, 0, 0.88)',
    colorBorder:            '#f0f0f0',
    colorBorderSecondary:   '#f0f0f0',
    colorPrimary:           '#1677ff',
    colorPrimaryHover:      '#4096ff',
    colorPrimaryActive:     '#0958d9',
    headerBg:               '#ffffff',
    headerFontSize:         '16px',
    headerLineHeight:       '1.5',
    headerPadding:          '16px 24px',
    headerPaddingVertical:  '16px',
    headerPaddingHorizontal:'24px',
    bodyPadding:            '24px',
    footerPadding:          '16px 24px',
    footerBg:               '#ffffff',
    footerPaddingVertical:  '16px',
    footerPaddingHorizontal:'24px',
    borderRadius:           '6px',
    borderRadiusLG:         '8px',
    boxShadow:              '-6px 0 16px 0 rgba(0, 0, 0, 0.08), -3px 0 6px -4px rgba(0, 0, 0, 0.12), -9px 0 28px 8px rgba(0, 0, 0, 0.05)',
    motionDurationMid:      '0.2s',
    motionDurationSlow:     '0.3s',
    padding:                '16px',
    paddingXS:              '8px',
    paddingSM:              '12px',
    marginXS:               '8px',
    gap:                    '8px',
    extraFontSize:          '14px',
    closeIconSize:          '16px',
    closeIconColor:         'rgba(0, 0, 0, 0.45)',
    closeIconColorHover:    'rgba(0, 0, 0, 0.88)',
  },
};

// ── V4 Less → V5 Token Map ────────────────────────────────────────────────
// Maps AntD v4 Less variable names to v5+ token names
const V4_LESS_TO_V5 = {
  '@primary-color':              'colorPrimary',
  '@success-color':              'colorSuccess',
  '@warning-color':              'colorWarning',
  '@error-color':                'colorError',
  '@info-color':                 'colorInfo',
  '@highlight-color':            'colorError',
  '@normal-color':               '#d9d9d9',

  '@text-color':                 'colorText',
  '@text-color-secondary':       'colorTextSecondary',
  '@text-color-inverse':         '#ffffff',
  '@text-color-dark':            'rgba(0, 0, 0, 0.85)',
  '@text-color-secondary-dark':  'rgba(0, 0, 0, 0.65)',

  '@heading-color':              'rgba(0, 0, 0, 0.88)',
  '@heading-color-dark':         'rgba(255, 255, 255, 0.85)',

  '@border-color-base':          'colorBorder',
  '@border-color-split':         'colorBorderSecondary',
  '@border-color-inverse':       '#ffffff',
  '@border-radius-base':         'borderRadius',
  '@border-radius-sm':           '4px',
  '@border-radius-lg':           '8px',

  '@background-color-base':      '#f5f5f5',
  '@background-color-light':     '#fafafa',
  '@background-color-dark':      '#1c1c1c',
  '@body-background':            '#ffffff',
  '@component-background':       'colorBgContainer',
  '@popover-background':         'colorBgElevated',
  '@tooltip-bg':                 'colorBgSpotlight',

  '@font-size-base':             'fontSize',
  '@font-size-sm':               'fontSizeSM',
  '@font-size-lg':               'fontSizeLG',
  '@font-family':                'fontFamily',
  '@font-family-code':           'fontFamilyCode',
  '@line-height-base':           'lineHeight',
  '@line-height-lg':             'lineHeightLG',
  '@line-height-sm':             'lineHeightSM',

  '@padding-lg':                 '24px',
  '@padding-md':                 '16px',
  '@padding-sm':                 '12px',
  '@padding-xs':                 '8px',
  '@padding-xxs':                '4px',
  '@margin-lg':                  '24px',
  '@margin-md':                  '16px',
  '@margin-sm':                  '12px',
  '@margin-xs':                  '8px',
  '@margin-xxs':                 '4px',
  '@margin-xl':                  '32px',
  '@margin-xxl':                 '48px',

  '@height-base':                'controlHeight',
  '@height-sm':                  'controlHeightSM',
  '@height-lg':                  'controlHeightLG',
  '@control-padding-horizontal': 'controlPaddingHorizontal',
  '@control-padding-horizontal-sm': 'controlPaddingHorizontalSM',
  '@outline-width':              'controlOutlineWidth',
  '@outline-color':              'controlOutline',
  '@input-outline-offset':       '0 0',
  '@input-height-base':          'controlHeight',
  '@input-height-sm':            'controlHeightSM',
  '@input-height-lg':            'controlHeightLG',

  '@btn-primary-color':          '#ffffff',
  '@btn-primary-bg':             'colorPrimary',
  '@btn-primary-border':         'colorPrimary',
  '@btn-default-color':          'rgba(0, 0, 0, 0.88)',
  '@btn-default-bg':             '#ffffff',
  '@btn-default-border':         '#d9d9d9',
  '@btn-danger-color':           '#ffffff',
  '@btn-danger-bg':              '#ff4d4f',
  '@btn-danger-border':          '#ff4d4f',
  '@btn-border-radius-base':     'borderRadius',
  '@btn-font-size-lg':           '16px',
  '@btn-font-size-sm':           '14px',
  '@btn-height-base':            'controlHeight',
  '@btn-height-sm':              'controlHeightSM',
  '@btn-height-lg':              'controlHeightLG',
  '@btn-padding-horizontal-base':'15px',
  '@btn-padding-horizontal-sm':  '7px',
  '@btn-padding-horizontal-lg':  '15px',

  '@table-header-bg':            '#fafafa',
  '@table-header-color':         'rgba(0, 0, 0, 0.88)',
  '@table-row-hover-bg':         '#fafafa',
  '@table-selected-row-bg':      '#e6f4ff',
  '@table-body-sort-bg':         '#fafafa',
  '@table-header-sort-bg':       '#f0f0f0',
  '@table-header-filter-bg':     '#f0f0f0',
  '@table-border-color':         '#f0f0f0',
  '@table-bg':                   '#ffffff',
  '@table-footer-bg':            '#fafafa',
  '@table-footer-color':         'rgba(0, 0, 0, 0.88)',
  '@table-expanded-row-bg':      '#fafafa',

  '@input-color':                'rgba(0, 0, 0, 0.88)',
  '@input-placeholder-color':    'rgba(0, 0, 0, 0.25)',
  '@input-bg':                   '#ffffff',
  '@input-border-color':         '#d9d9d9',
  '@input-hover-border-color':   '#4096ff',
  '@input-active-border-color':  '#4096ff',
  '@input-disabled-bg':          'rgba(0, 0, 0, 0.04)',
  '@input-addon-bg':             'rgba(0, 0, 0, 0.02)',

  '@card-head-color':            'rgba(0, 0, 0, 0.88)',
  '@card-head-background':       'transparent',
  '@card-padding-base':          '24px',
  '@card-padding-base-sm':       '12px',
  '@card-background':            '#ffffff',
  '@card-shadow':                '0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)',
  '@card-radius':                'borderRadius',
  '@card-actions-background':    '#ffffff',

  '@modal-header-bg':            '#ffffff',
  '@modal-header-border-color-split': '#f0f0f0',
  '@modal-content-bg':           '#ffffff',
  '@modal-footer-bg':            'transparent',
  '@modal-footer-border-color-split': '#f0f0f0',
  '@modal-mask-bg':              'rgba(0, 0, 0, 0.45)',
  '@modal-body-padding':         '24px',
  '@modal-header-padding':       '16px 24px',
  '@modal-footer-padding':       '16px 24px',
  '@modal-border-radius':        '6px',
  '@modal-close-color':          'rgba(0, 0, 0, 0.45)',

  '@tabs-card-head-background':  '#fafafa',
  '@tabs-ink-bar-color':         'colorPrimary',
  '@tabs-active-color':          'colorPrimary',
  '@tabs-hover-color':           'colorPrimaryHover',
  '@tabs-highlight-color':       'colorPrimary',
  '@tabs-title-font-size':       '14px',
  '@tabs-title-font-size-lg':    '16px',
  '@tabs-horizontal-gutter':     '32px',
  '@tabs-horizontal-margin':     '0 0 0 32px',
  '@tabs-card-height':           '40px',

  '@menu-dark-bg':               '#001529',
  '@menu-dark-submenu-bg':       '#000c17',
  '@menu-dark-item-color':       'rgba(255, 255, 255, 0.65)',
  '@menu-dark-item-active-bg':   '#1677ff',
  '@menu-dark-item-hover-bg':    'transparent',
  '@menu-dark-highlight-color':  '#ffffff',
  '@menu-dark-selected-item-icon-color': '#ffffff',
  '@menu-dark-selected-item-text-color': '#ffffff',
  '@menu-bg':                    '#ffffff',
  '@menu-popup-bg':              '#ffffff',
  '@menu-item-color':            'rgba(0, 0, 0, 0.88)',
  '@menu-item-active-bg':        '#e6f4ff',
  '@menu-item-active-border-width': '0px',
  '@menu-highlight-color':       '#1677ff',
  '@menu-horizontal-line-height': '46px',
  '@menu-inline-submenu-bg':     '#ffffff',
  '@menu-collapsed-width':       '48px',
  '@menu-item-padding':          '0 16px',
  '@menu-item-vertical-margin':  '4px',
  '@menu-item-boundary-margin':  '4px',
  '@menu-icon-size':             '16px',
  '@menu-icon-size-collapsed':   '16px',
  '@menu-item-height':           '40px',

  '@form-item-margin-bottom':    '24px',
  '@form-item-margin-bottom-sm': '16px',
  '@form-vertical-label-padding':'0 0 4px',
  '@form-label-color':           'rgba(0, 0, 0, 0.88)',
  '@form-label-font-size':       '14px',
  '@form-label-required-color':  '#ff4d4f',

  '@tag-default-bg':             '#fafafa',
  '@tag-default-color':          'rgba(0, 0, 0, 0.88)',
  '@tag-font-size':              '12px',
  '@tag-line-height':            '1.5',
  '@tag-border-radius':          '4px',

  '@badge-height':               '20px',
  '@badge-height-sm':            '14px',
  '@badge-dot-size':             '6px',
  '@badge-font-size':            '12px',
  '@badge-status-size':          '6px',
  '@badge-text-font-size':       '12px',
  '@badge-text-font-weight':     '400',

  '@checkbox-size':              '16px',
  '@checkbox-color':             '#1677ff',
  '@checkbox-border-color':      '#d9d9d9',
  '@checkbox-check-color':       '#ffffff',
  '@checkbox-check-bg':          '#1677ff',

  '@radio-size':                 '16px',
  '@radio-dot-color':            '#1677ff',
  '@radio-dot-size':             '8px',
  '@radio-button-bg':            '#ffffff',
  '@radio-button-color':         'rgba(0, 0, 0, 0.88)',
  '@radio-button-checked-bg':    '#ffffff',
  '@radio-button-checked-color': '#1677ff',

  '@switch-color':               'colorPrimary',
  '@switch-bg':                  'colorPrimary',
  '@switch-shadow':              '0 2px 4px 0 rgba(0, 35, 11, 0.2)',
  '@switch-sm-min-width':        '28px',
  '@switch-min-width':           '44px',
  '@switch-height':              '22px',
  '@switch-sm-height':           '16px',
  '@switch-handle-size':         '18px',
  '@switch-handle-sm-size':      '12px',

  '@slider-track-background-color':       'colorPrimary',
  '@slider-track-background-color-hover': 'colorPrimaryHover',
  '@slider-handle-color':                 'colorPrimary',
  '@slider-handle-color-hover':           'colorPrimaryHover',
  '@slider-handle-color-active':          'colorPrimaryActive',
  '@slider-rail-background-color':        'rgba(0, 0, 0, 0.06)',
  '@slider-rail-background-color-hover':  'rgba(0, 0, 0, 0.06)',
  '@slider-dot-border-color':             '#d9d9d9',
  '@slider-dot-border-color-active':      'colorPrimary',
  '@slider-handle-size':                  '14px',
  '@slider-handle-size-hover':            '16px',

  '@progress-default-color':   'colorPrimary',
  '@progress-remaining-color': 'rgba(0, 0, 0, 0.06)',
  '@progress-text-color':      'rgba(0, 0, 0, 0.88)',
  '@progress-circle-text-font-size': '24px',

  '@tooltip-color':            '#ffffff',
  '@tooltip-bg':               '#000000',
  '@tooltip-border-radius':    '4px',
  '@tooltip-distance':         '8px',
  '@tooltip-padding':          '6px 8px',
  '@tooltip-arrow-color':      '#000000',

  '@popover-color':            'rgba(0, 0, 0, 0.88)',
  '@popover-bg':               '#ffffff',
  '@popover-min-width':        '177px',
  '@popover-arrow-color':      '#ffffff',
  '@popover-arrow-width':      '12px',
  '@popover-border-color':     '#f0f0f0',
  '@popover-distance':         '8px',
  '@popover-padding-horizontal':'16px',

  '@drawer-header-padding':          '16px 24px',
  '@drawer-body-padding':            '24px',
  '@drawer-footer-padding':          '16px 24px',
  '@drawer-bg':                      '#ffffff',
  '@drawer-header-bg':               '#ffffff',
  '@drawer-footer-bg':               '#ffffff',
  '@drawer-mask-bg':                 'rgba(0, 0, 0, 0.45)',
  '@drawer-title-font-size':         '16px',
  '@drawer-close-color':             'rgba(0, 0, 0, 0.45)',

  '@date-picker-color':              'rgba(0, 0, 0, 0.88)',
  '@date-picker-cell-hover-bg':      'rgba(0, 0, 0, 0.04)',
  '@date-picker-cell-active-bg':     '#e6f4ff',
  '@date-picker-input-bg':           '#ffffff',
  '@date-picker-border-color':       '#d9d9d9',
  '@date-picker-active-border-color':'#4096ff',
  '@date-picker-hover-border-color': '#4096ff',

  '@shadow-color':                   'rgba(0, 0, 0, 0.15)',
  '@shadow-color-inverse':           'rgba(255, 255, 255, 0.8)',
  '@box-shadow-base':                '0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)',
  '@shadow-1-up':                    '0 -6px 16px 0 rgba(0, 0, 0, 0.08), 0 -3px 6px -4px rgba(0, 0, 0, 0.12), 0 -9px 28px 8px rgba(0, 0, 0, 0.05)',
  '@shadow-1-down':                  '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
  '@shadow-1-left':                  '-6px 0 16px 0 rgba(0, 0, 0, 0.08), -3px 0 6px -4px rgba(0, 0, 0, 0.12), -9px 0 28px 8px rgba(0, 0, 0, 0.05)',
  '@shadow-1-right':                 '6px 0 16px 0 rgba(0, 0, 0, 0.08), 3px 0 6px -4px rgba(0, 0, 0, 0.12), 9px 0 28px 8px rgba(0, 0, 0, 0.05)',
  '@shadow-2':                       '0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',

  '@ease-base-out':                  'cubic-bezier(0.7, 0.3, 0.1, 1)',
  '@ease-base-in':                   'cubic-bezier(0.9, 0, 0.3, 0.7)',
  '@ease-in-out':                    'cubic-bezier(0.05, 0, 0.35, 1)',
  '@ease-out':                       'cubic-bezier(0.15, 0.6, 0.35, 1)',
  '@ease-in':                        'cubic-bezier(0.55, 0.08, 0.68, 0.53)',
  '@ease-out-back':                  'cubic-bezier(0.34, 1.56, 0.64, 1)',
  '@ease-in-back':                   'cubic-bezier(0.36, 0, 0.66, -0.56)',

  '@animation-duration-slow':        '0.3s',
  '@animation-duration-base':        '0.2s',
  '@animation-duration-fast':        '0.1s',

  '@font-size-heading-1':            '38px',
  '@font-size-heading-2':            '30px',
  '@font-size-heading-3':            '24px',
  '@font-size-heading-4':            '20px',
  '@font-size-heading-5':            '16px',
  '@font-weight-strong':             '600',

  '@white':                          '#ffffff',
  '@black':                          '#000000',
  '@blue':                           '#1677ff',
  '@purple':                         '#722ed1',
  '@cyan':                           '#13c2c2',
  '@green':                          '#52c41a',
  '@magenta':                        '#eb2f96',
  '@pink':                           '#eb2f96',
  '@red':                            '#ff4d4f',
  '@orange':                         '#fa8c16',
  '@yellow':                          '#fadb14',
  '@volcano':                        '#fa541c',
  '@geekblue':                       '#2f54eb',
  '@lime':                           '#a0d911',
  '@gold':                           '#faad14',
};

// ── V6 Known Changes ──────────────────────────────────────────────────────
// Based on AntD v6 alpha changelogs:
// - Renamed colorTextQuaternary → colorTextDisabled
// - New heading token: fontSizeHeading1-6 with adjusted values
// - New borderRadiusOuter, borderRadiusInner
// - New motion tokens: motionDurationExtraFast, motionDurationExtraSlow
// - New colorBgCell, colorBgInput, colorBgPopover
const V6_TOKEN_DELTA = {
  // Renamed/removed
  removed: ['colorTextQuaternary'],
  renamed: {
    colorTextQuaternary: 'colorTextDisabled',
    colorFillQuaternary: 'colorFillDisabled',
  },
  // New tokens
  added: {
    colorTextDisabled:    'rgba(0, 0, 0, 0.25)',
    colorFillDisabled:    'rgba(0, 0, 0, 0.02)',

    // New heading sizes (tighter scale)
    fontSizeHeading1:     '36px',
    fontSizeHeading2:     '28px',
    fontSizeHeading3:     '22px',
    fontSizeHeading4:     '18px',
    fontSizeHeading5:     '14px',
    fontSizeHeading6:     '12px',

    // New border radii
    borderRadiusOuter:    '8px',
    borderRadiusInner:    '4px',

    // Motion
    motionDurationExtraFast: '0.05s',
    motionDurationExtraSlow: '0.4s',

    // Background variants
    colorBgCell:          '#fafafa',
    colorBgInput:         '#ffffff',
    colorBgPopover:       '#ffffff',
    colorBgTooltip:       '#000000',
  },
  // Changed default values
  changed: {
    borderRadius:         '8px',
    controlHeight:        '34px',
    controlHeightSM:      '26px',
    controlHeightLG:      '42px',
    boxShadow:            '0 1px 3px 0 rgba(0, 0, 0, 0.04), 0 1px 2px -1px rgba(0, 0, 0, 0.03)',
  },
};

// ── Component List ─────────────────────────────────────────────────────────
const SUPPORTED_COMPONENTS = Object.keys(COMPONENT_TOKENS);

// ── Class → Component Mapping ─────────────────────────────────────────────
const CLASS_TO_COMPONENT = {
  'ant-btn':                'Button',
  'ant-btn-primary':        'Button',
  'ant-btn-default':        'Button',
  'ant-btn-dashed':         'Button',
  'ant-btn-link':           'Button',
  'ant-btn-text':           'Button',
  'ant-btn-dangerous':      'Button',
  'ant-btn-ghost':          'Button',
  'ant-input':              'Input',
  'ant-input-affix-wrapper':'Input',
  'ant-input-group':        'Input',
  'ant-input-search':       'Input',
  'ant-input-textarea':     'Input',
  'ant-input-password':     'Input',
  'ant-select':             'Select',
  'ant-select-selector':    'Select',
  'ant-select-selection':   'Select',
  'ant-select-dropdown':    'Select',
  'ant-table':              'Table',
  'ant-table-container':    'Table',
  'ant-table-thead':        'Table',
  'ant-table-tbody':        'Table',
  'ant-table-row':          'Table',
  'ant-table-cell':         'Table',
  'ant-table-header':       'Table',
  'ant-card':               'Card',
  'ant-card-head':          'Card',
  'ant-card-body':          'Card',
  'ant-card-actions':       'Card',
  'ant-card-grid':          'Card',
  'ant-modal':              'Modal',
  'ant-modal-content':      'Modal',
  'ant-modal-header':       'Modal',
  'ant-modal-body':         'Modal',
  'ant-modal-footer':       'Modal',
  'ant-modal-mask':         'Modal',
  'ant-tag':                'Tag',
  'ant-badge':              'Badge',
  'ant-badge-count':        'Badge',
  'ant-badge-dot':          'Badge',
  'ant-badge-status':       'Badge',
  'ant-tabs':               'Tabs',
  'ant-tabs-tab':           'Tabs',
  'ant-tabs-tabpane':       'Tabs',
  'ant-tabs-nav':           'Tabs',
  'ant-tabs-ink-bar':       'Tabs',
  'ant-menu':               'Menu',
  'ant-menu-item':          'Menu',
  'ant-menu-submenu':       'Menu',
  'ant-menu-sub':           'Menu',
  'ant-menu-item-group':    'Menu',
  'ant-menu-horizontal':    'Menu',
  'ant-menu-vertical':      'Menu',
  'ant-menu-inline':        'Menu',
  'ant-form':               'Form',
  'ant-form-item':          'Form',
  'ant-form-item-label':    'Form',
  'ant-form-item-control':  'Form',
  'ant-form-label':         'Form',
  'ant-form-explain':       'Form',
  'ant-form-extra':         'Form',
  'ant-picker':             'DatePicker',
  'ant-picker-dropdown':    'DatePicker',
  'ant-picker-panel':       'DatePicker',
  'ant-picker-cell':        'DatePicker',
  'ant-picker-header':      'DatePicker',
  'ant-picker-body':        'DatePicker',
  'ant-picker-footer':      'DatePicker',
  'ant-checkbox':           'Checkbox',
  'ant-checkbox-wrapper':   'Checkbox',
  'ant-checkbox-input':     'Checkbox',
  'ant-checkbox-group':     'Checkbox',
  'ant-radio':              'Radio',
  'ant-radio-wrapper':      'Radio',
  'ant-radio-button':       'Radio',
  'ant-radio-group':        'Radio',
  'ant-radio-input':        'Radio',
  'ant-switch':             'Switch',
  'ant-slider':             'Slider',
  'ant-slider-rail':        'Slider',
  'ant-slider-track':       'Slider',
  'ant-slider-handle':      'Slider',
  'ant-slider-mark':        'Slider',
  'ant-slider-step':        'Slider',
  'ant-progress':           'Progress',
  'ant-progress-line':      'Progress',
  'ant-progress-circle':    'Progress',
  'ant-progress-steps':     'Progress',
  'ant-progress-text':      'Progress',
  'ant-tooltip':            'Tooltip',
  'ant-tooltip-content':    'Tooltip',
  'ant-tooltip-arrow':      'Tooltip',
  'ant-tooltip-inner':      'Tooltip',
  'ant-popover':            'Popover',
  'ant-popover-content':    'Popover',
  'ant-popover-arrow':      'Popover',
  'ant-popover-inner':      'Popover',
  'ant-popover-title':      'Popover',
  'ant-popover-inner-content':'Popover',
  'ant-drawer':             'Drawer',
  'ant-drawer-content':     'Drawer',
  'ant-drawer-header':      'Drawer',
  'ant-drawer-body':        'Drawer',
  'ant-drawer-footer':      'Drawer',
  'ant-drawer-mask':        'Drawer',
};

// ── Seed → Map → Component Derivation Map ─────────────────────────────────
// Describes which component tokens are derived from which seed tokens.
// Used to trace token provenance.
const SEED_TO_COMPONENT_DERIVATION = {
  colorPrimary: {
    mapDerived: [
      'colorPrimaryBg', 'colorPrimaryBgHover',
      'colorPrimaryBorder', 'colorPrimaryBorderHover',
      'colorPrimaryHover', 'colorPrimaryActive',
      'colorPrimaryText', 'colorPrimaryTextHover', 'colorPrimaryTextActive',
    ],
    componentUses: {
      Button:    ['colorPrimary', 'colorPrimaryHover', 'colorPrimaryActive', 'primaryShadow'],
      Table:     ['rowSelectedBg', 'rowSelectedHoverBg'],
      Tag:       ['colorPrimary', 'colorPrimaryBg', 'colorPrimaryBorder'],
      Tabs:      ['colorPrimary', 'colorPrimaryHover', 'colorPrimaryActive', 'inkBarColor', 'itemSelectedColor'],
      Menu:      ['colorPrimary', 'colorPrimaryHover', 'colorPrimaryActive', 'itemSelectedColor', 'itemSelectedBg'],
      Checkbox:  ['colorPrimary', 'colorPrimaryHover', 'colorPrimaryActive', 'checkboxCheckColor'],
      Radio:     ['colorPrimary', 'colorPrimaryHover', 'colorPrimaryActive', 'radioCheckColor', 'buttonCheckedColor', 'buttonSolidCheckedBg'],
      Switch:    ['colorPrimary', 'colorPrimaryHover', 'colorPrimaryActive'],
      Slider:    ['colorPrimary', 'colorPrimaryHover', 'colorPrimaryActive', 'trackBg', 'trackHoverBg', 'handleColor'],
      Progress:  ['colorPrimary', 'defaultStrokeColor', 'stepColor'],
      Modal:     ['colorPrimary', 'colorPrimaryHover'],
      Drawer:    ['colorPrimary', 'colorPrimaryHover', 'colorPrimaryActive'],
      DatePicker:['colorPrimary', 'colorPrimaryHover', 'colorPrimaryActive', 'colorLink', 'cellActiveBg'],
      Input:     ['colorPrimary', 'colorPrimaryHover', 'activeBorderColor', 'hoverBorderColor'],
      Select:    ['colorPrimary', 'colorPrimaryHover', 'optionSelectedBg', 'activeBorderColor', 'hoverBorderColor'],
    },
  },
  borderRadius: {
    componentUses: {
      Button:    ['borderRadius'],
      Input:     ['borderRadius'],
      Select:    ['borderRadius'],
      Card:      ['borderRadius'],
      Modal:     ['borderRadius', 'borderRadiusLG'],
      Tag:       ['borderRadius'],
      Badge:     ['borderRadius', 'borderRadiusSM'],
      Tabs:      ['borderRadius'],
      Menu:      ['borderRadius', 'horizontalItemBorderRadius', 'verticalItemBorderRadius'],
      Form:      ['borderRadius'],
      DatePicker:['borderRadius'],
      Checkbox:  ['borderRadius'],
      Switch:    ['borderRadius', 'borderRadiusSM'],
      Slider:    ['borderRadius'],
      Progress:  ['borderRadius'],
      Tooltip:   ['borderRadius'],
      Popover:   ['borderRadius'],
      Drawer:    ['borderRadius', 'borderRadiusLG'],
      Table:     ['headerBorderRadius'],
    },
  },
};

// ── Exports ────────────────────────────────────────────────────────────────
module.exports = {
  SEED_TOKENS,
  MAP_TOKENS,
  ALIAS_TOKENS,
  COMPONENT_TOKENS,
  V4_LESS_TO_V5,
  V6_TOKEN_DELTA,
  SUPPORTED_COMPONENTS,
  CLASS_TO_COMPONENT,
  SEED_TO_COMPONENT_DERIVATION,
};